[package]
name = "flexml_root"
description = "Quickly and easily define namespaced XML serialization"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
flexml = {  path = "./flexml", features = ["macro"]}

[workspace]
resolver = "2"
members = [
	"flexml",
	"flexml_macro",
]
