[package]
name = "flexml_root"
version = "0.0.0"
edition = "2021"

[dependencies]
flexml = { path = "./flexml", features = ["macro"]}

[workspace]
resolver = "2"
members = [
	"flexml",
	"flexml_macro",
]
